add checking

diff --git a/gh-repo-stats b/gh-repo-stats
--- a/gh-repo-stats
+++ b/gh-repo-stats
@@ -1435,6 +1435,18 @@ ValidateJQ()
   fi
 }
 ################################################################################
+#### Function ValidateInput ####################################################
+################################################################################
+ValidateInput()
+{
+  if [[ $OUTPUT != "Table" ]] && [[ $OUTPUT != "CSV" ]]; then
+    echo "Output parameter (-o, --output) '${OUTPUT}' is invalid. Must be 'CSV' or 'Table'"
+    exit 1;
+  fi
+}
+
+
+################################################################################
 ############################## MAIN ############################################
 ################################################################################
 
@@ -1447,6 +1459,11 @@ Header
 # Validate JQ installed #
 #########################
 ValidateJQ
+
+#############################
+# Validate Input Parameters #
+#############################
+ValidateInput
 
 #################
 # Generate File #
